### ISSUE TITLE
Querying views without documents

### ISSUE THREAD

**Issue by nielsboldt** [mathieuancelin/play2-couchbase#21]
Hi,

I'm trying to query a view with a reducer so response contains no documents.

I'm trying to use the _search_ methods in client wrapper but always get the error

<b>
[info] ! be able to read summation statistics on trackings
[error]     UnsupportedOperationException: Reduced views don't contain documents
 (ViewRowReduced.java:63)
[error] com.couchbase.client.protocol.views.ViewRowReduced.getDocument(ViewRowRe
duced.java:63)
[error] com.couchbase.client.protocol.views.ViewRowReduced.getDocument(ViewRowRe
duced.java:29)
[error] org.ancelin.play2.couchbase.ClientWrapper$$anonfun$rawSearch$2$$anonfun$
apply$9.apply(ClientWrapper.scala:103)
[error] org.ancelin.play2.couchbase.ClientWrapper$$anonfun$rawSearch$2$$anonfun$
apply$9.apply(ClientWrapper.scala:103)
[error] play.api.libs.iteratee.Input$class.map(Iteratee.scala:233)
</b>

I looked through the code and it looks like all search call always end into the method

``` scala
  def rawSearch(view: View)(query: Query)(implicit bucket: CouchbaseBucket, ec: ExecutionContext): QueryEnumerator[RawRow] = {
    QueryEnumerator(wrapJavaFutureInPureFuture( bucket.couchbaseClient.asyncQuery(view, query), ec ).map { results =>
      Enumerator.enumerate(results.iterator()) &> Enumeratee.map[ViewRow](r => RawRow(r.getDocument.asInstanceOf[String], r.getId, r.getKey, r.getValue))
    })
  }

```

which calls getDocument on the row

Is it really true that the plugin don't expose any functionality to query reduced views or have I overlooked something here

Thanks
Niels

**Comment by mathieuancelin** [comment]
Hi Niels,

Can you show me how you build your query ?

I suspect that you didn't call `.setIncludeDocs(true)` on it, so the Query can't fetch the documents. Anyway the plugin should ensure that it's done before sending the query to the server, I will fill an issue about it.

If it's not working either, can you provide me more details about your use case so I can reproduce the issue ?

Thanks

**Comment by nielsboldt** [comment]
I build my query like

´´´scala
    def readUserAgentTrackingsAncelin = {
         val q = new Query().setIncludeDocs(false).setStale(Stale.FALSE).setReduce(true).setGroup(true)
         bucket.search( ipUserAgentView )( q ).toList
    }
´´´
I get the exception

<b>
[info] ! recreate bug for issue
[error]     UnsupportedOperationException: Reduced views don't contain documents
 (ViewRowReduced.java:63)
[error] com.couchbase.client.protocol.views.ViewRowReduced.getDocument(ViewRowRe
duced.java:63)
[error] com.couchbase.client.protocol.views.ViewRowReduced.getDocument(ViewRowRe
duced.java:29)
[error] org.ancelin.play2.couchbase.ClientWrapper$$anonfun$rawSearch$2$$anonfun$
apply$9.apply(ClientWrapper.scala:103)
[error] org.ancelin.play2.couchbase.ClientWrapper$$anonfun$rawSearch$2$$anonfun$
apply$9.apply(ClientWrapper.scala:103)
[error] play.api.libs.iteratee.Input$class.map(Iteratee.scala:233)
[error] play.api.libs.iteratee.Input$El.map(Iteratee.scala:244)
[error] play.api.libs.iteratee.Enumeratee$$anon$45$$anonfun$apply$23.apply(Enume
ratee.scala:373)
[error] play.api.libs.iteratee.Enumeratee$$anon$45$$anonfun$apply$23.apply(Enume
ratee.scala:373)
[error] play.api.libs.iteratee.Enumeratee$$anon$38$$anon$1$$anonfun$play$api$lib
s$iteratee$Enumeratee$$anon$$anon$$step$1$$anonfun$apply$11.apply(Enumeratee.sca
la:203)
[error] play.api.libs.iteratee.Enumeratee$$anon$38$$anon$1$$anonfun$play$api$lib
s$iteratee$Enumeratee$$anon$$anon$$step$1$$anonfun$apply$11.apply(Enumeratee.sca
la:203)
[error] akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
[error] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abstrac
tDispatcher.scala:386)
</b>

My view is like

<b>
       "useragent" : {
           "map" : " function (doc, meta) { \n \n var idSplitted = meta.id.match(/t\/(\d+)\/(\d+)/); \n if( idSplitted && doc.ua && doc.ip ){ \n   var userId = idSplitted[1];\n var timestamp = idSplitted[2];\n var asDate = new Date(parseInt(timestamp)); \n emit([asDate.getUTCFullYear(),asDate.getUTCMonth(),asDate.getUTCDate(),asDate.getUTCHours(),doc.ip,doc.ua], null ); \n } \n}",
           "reduce" : "_count"
       },
</b>

But I'm running a full reduce so there is no correspondance between the key in the result and the actual document. 

Is the problem that I'm using a wrong method. Why is the client insisting on getting a document when response don't contain any?

/Niels

**Comment by mathieuancelin** [comment]
Ok, 

so I guess that the find method is not what you're looking for because it always try to fetch the document and bind it to a Scala object through a JSON deserializer.

You should use `rawSearch` that will allow you to get a representation of the result with the id, the key and the value.

But right now it will not work since the `rawSearch` method try to get the document.

I will publish a patch to fix that ASAP, and then you'll be able to get the result of the count in the value of the `RawRow`

**Comment by mathieuancelin** [comment]
I just updated the library artifacts, so you can try the `rawSearch` function instead of search.

Let me know if it works.

**Comment by nielsboldt** [comment]
Yes, it works now.

Thanks
Niels

**Comment by mathieuancelin** [comment]
Cool :-)
