### ISSUE TITLE
N1QL support?

### ISSUE THREAD

**Issue by cocodrino** [mathieuancelin/play2-couchbase#34]
Hi mathieu..would be possible add n1ql support in a near future??...n1ql looks promising although not full stable yet...there is an extension for the java api

https://github.com/daschl/couchbase-java-query

thanks!!...

**Comment by mathieuancelin** [comment]
Hi,

actually, N1QL is already supported 

https://github.com/mathieuancelin/play2-couchbase/blob/master/attic/README.md#couchbase-n1ql-search

but this project is now dead, if you want to use the new version, see https://github.com/ReactiveCouchbase

**Comment by cocodrino** [comment]
that is fantastic...probably the best lib for couchbase than I've seen, thanks so much mathieu...I will try it.....
